# Generated by Django 6.0.2 on 2026-02-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilagente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidormonitorado',
            name='data_cadastro',
        ),
    ]
