# Generated by Django 6.0.2 on 2026-02-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_servidormonitorado_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidormonitorado',
            name='unidade',
            field=models.CharField(default='PENDENTE', max_length=100),
            preserve_default=False,
        ),
    ]
