# Generated by Django 6.0.2 on 2026-02-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servidormonitorado_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidormonitorado',
            name='unidade',
            field=models.CharField(default='PENDENTE', max_length=100),
        ),
    ]
