# Generated by Django 5.1.3 on 2026-03-05 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_servidormonitorado_unidade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegraClassificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gatilho",
                    models.CharField(
                        help_text="Palavra lida no BI (Ex: CONVOCAÇÃO)", max_length=100
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        help_text="Nome do Card (Ex: CONVOCAÇÃO PARA DEPOR)",
                        max_length=100,
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("slate", "Cinza Neutro (Sem Classificação)"),
                            ("rose", "Vermelho (Ex: Exoneração, Convocação)"),
                            ("amber", "Amarelo (Ex: Promoção, Elogio)"),
                            ("emerald", "Verde (Ex: Férias, Licença)"),
                            ("blue", "Azul (Ex: Majoração)"),
                            ("violet", "Roxo (Ex: Designação)"),
                            ("stone", "Preto (Ex: Falecimento)"),
                        ],
                        default="slate",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermoMonitorado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("termo", models.CharField(max_length=100)),
                (
                    "agente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
