# Generated by Django 5.1.3 on 2026-03-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_regraclassificacao_termomonitorado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regraclassificacao",
            name="cor",
            field=models.CharField(
                choices=[
                    ("slate", "Cinza Neutro (Sem Classificação)"),
                    ("rose", "Vermelho (Ex: Exoneração, Convocação)"),
                    ("amber", "Amarelo (Ex: Promoção, Elogio)"),
                    ("emerald", "Verde (Ex: Férias, Licença)"),
                    ("blue", "Azul (Ex: Majoração)"),
                    ("violet", "Roxo (Ex: Designação)"),
                    ("stone", "Preto (Ex: Falecimento)"),
                    ("orange", "Laranja (Ex: Atenção)"),
                    ("pink", "Rosa (Ex: Destaque Especial)"),
                    ("indigo", "Índigo (Ex: Transferência)"),
                ],
                default="slate",
                max_length=20,
            ),
        ),
    ]
