# Generated by Django 5.1.3 on 2026-03-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_regraclassificacao_cor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servidormonitorado",
            options={"ordering": ["nome"]},
        ),
        migrations.AddField(
            model_name="servidormonitorado",
            name="tratamento",
            field=models.CharField(
                blank=True,
                choices=[("", "Nenhum"), ("Dr.", "Dr."), ("Dra.", "Dra.")],
                default="",
                max_length=10,
            ),
        ),
    ]
